config/routes.rb
Rails.application.routes.draw do
  resources :hikings do
    resources :reviews
  end
  resources :refuges do
    resources :availabilities
    resources :reviews
    resources :bookings do
      resources :payments, only: [:new, :create] do
        collection do
          get 'confirmation'
        end
      end
    end
  end
  resource :profile, controller: 'profile'


  get 'my_refuges', to: 'refuges#my_refuges'
  get 'my_bookings', to: 'bookings#my_bookings'
  resources :bookings, only: [:index] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/refuge.rb
class Refuge < ApplicationRecord
  belongs_to :user
  has_many :availabilities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :guides
  has_many :refuge_to_hikes
  has_many :hikings, through: :refuge_to_hikes
  has_many :reviews, as: :reviewable, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  monetize :price_cents

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    if search
     return self.near(search, 50)
    else
      return Refuge.all
    end
    return nil
  end

  def availability
    capacity - bookings
  end
end

app/controllers/refuges_controller.rb
class RefugesController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]
  skip_after_action :verify_authorized, only:[:index, :show]
  before_action :set_refuge, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only: :my_refuges
  # GET /refuges
  # GET /refuges.json
  def index
    @refuges = policy_scope(Refuge).search(params[:search]).where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@refuges) do |refuge, marker|
      marker.lat refuge.latitude
      marker.lng refuge.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
      authorize @refuges
    end
  end

  def my_refuges
    @user = current_user
    @refuges = @user.refuges
  end
  # GET /refuges/1
  def show
    date_killer
    @availability = Availability.new
    @availabilities = Availability.all
    @refuges = Refuge.all
    @refuge = Refuge.find(params[:id])
    @refuge_coordinates = { lat: @refuge.latitude, lng: @refuge.longitude }

    @booking = Booking.new
    @review = Review.new
    authorize @refuge

    @refuge_coordinates = { lat: @refuge.latitude, lng: @refuge.longitude }

    @hash = Gmaps4rails.build_markers(@refuge) do |refuge, marker|
      marker.lat refuge.latitude
      marker.lng refuge.longitude
    end
  end

  # GET /refuges/new
  def new
    @refuge = Refuge.new
    authorize @refuge
  end

  # GET /refuges/1/edit
  def edit
    @refuge = Refuge.find(params[:id])
    authorize @refuge
  end

  # POST /refuges
  def create
    @refuge = Refuge.new(refuge_params)
    @refuge.user = current_user
    authorize @refuge

    if @refuge.save
        redirect_to @refuge
    else
      render :new
    end
  end

  # PATCH/PUT /refuges/1
  # PATCH/PUT /refuges/1.json
  def update
    @refuge.update(refuge_params)

    if @refuge.save
      redirect_to @refuge
    else
      render :edit
    end
  end

  # DELETE /refuges/1
  # DELETE /refuges/1.json
  def destroy
    @refuge.destroy
    authorize @refuge
    respond_to do |format|
      format.html { redirect_to my_refuges_path, notice: 'Refuge was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refuge
     @refuge = Refuge.find(params[:id])
     authorize @refuge
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refuge_params
      params.require(:refuge).permit(:name, :photo, :photo_cache, :day_price, :capacity, :address, :description, :lat, :lon, :altitude, :range, :department, :price_cents)
    end



    def date_killer
    @availabilities = []
    @availabilities_formatted = []
    if Availability.all
      Availability.all.each do |availability|
        if availability.start_day && availability.end_day
          date = availability.start_day
          while date.strftime("%m/%d/%Y") <= availability.end_day.strftime("%m/%d/%Y")
            @availabilities << date.strftime("%m/%d/%Y")
            date += 1.day
          end
        end
      end
    end
  end
end

app/helpers/refuges_helper.rb
module RefugesHelper
end

app/views/refuges/_form.html.erb
        <%= simple_form_for(@refuge) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <div class="row">
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :name %>
            </div>
            <div class="col-sm-2"></div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :department %>
            </div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :address %>
            </div>
            <div class="col-sm-2"></div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
               <%= f.input :day_price %>
            </div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :capacity %>
            </div>
            <div class="col-sm-2"></div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :altitude %>
            </div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :range %>
            </div>
             <div class="col-sm-2"></div>
            <div class="form-group col-sm-4 col-xs-12" id="form-refuge">
              <%= f.input :description %>
            </div><br><br>
          </div>
          <div class="form-actions" id="create">
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %><br><br>
              <div id="refuge_cond"> <input type="checkbox" > I have read and accept the terms and conditions<br></div>
              <p></p>
              <%= f.button :submit %>
            </div>
      </div>
    <% end %>

app/views/refuges/edit.html.erb
<div class="banner-refuge" style="background: url('https://hd.unsplash.com/photo-1444201431989-0b9fa7488323');">


<div class="col-xs-12 col-sm-12" id="refuge">


    <%= render 'form', refuge: @refuge %>



</div>


</div>
<div class="text-center padded">

    <%= link_to 'Show', refuge_path, class: "btn btn-success" %>
    <%= link_to 'Back To Our Catalog', refuges_path, class: "btn btn-success" %>
  </div>

app/views/refuges/index.html.erb
<p id="notice"><%= notice %></p>

<section class="darkSection">
  <div class="container">
    <div class="row gridResize">
      <form action="<%=refuges_path %>" class="">
        <div class="col-sm-3 col-xs-12">
          <div class="sectionTitleDouble">
            <p>Find</p>
            <h2>your <span>shelter</span></h2>
          </div>
        </div>
        <div class="col-sm-7 col-xs-12">
          <div class="row">
            <div class="col-sm-6 col-xs-12">
              <div class="searchTour">
                <select name="guiest_id2" id="guiest_id2" class="select-drop">
                  <option value="0">Mountain Range</option>
                  <option value="1">Alpes</option>
                  <option value="2">Pyrenees</option>
                  <option value="3">Vosges</option>
                </select>
              </div>
            </div>
            <div class="col-sm-6 col-xs-12">
              <div class="input-group date ed-datepicker">
                <%= form_tag url_for(action: 'index', controller: 'refuges'), :id => 'search', :method => :get do %>
                <%= text_field_tag :search, params[:search], placeholder: "LOCATION"%>
              <div class="input-group-addon">
                <span class="fa fa-search"></span>
              </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <%= submit_tag "Search Shelter", :address => nil, class: "btn btn-success" %>
          <% end %>
        </div>
      </form>
    </div>
  </div>
</section>


<section class="mainContentSection packagesSection">
  <div class="container">
    <div class="row">
      <% @refuges.each do |refuge| %>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail deals">
        <%= cl_image_tag(refuge.photo,
      width: 400, height: 300, crop: :fill) %>
          <div class="discountInfo">
            <ul class="list-inline rating homePage">
            <% i = 0 %>
            <% ratingtotal = 0 %>
            <% refuge.reviews.each do |r| %>
            <% i += 1 %>
            <% ratingtotal += r.rating if r.rating != nil %>
            <% end %>
            <% i = ratingtotal / i if i != 0 %>
            <% i.to_i.times do %>
            <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - i.to_i).times do %>
            <i class="fa fa-star-o " aria-hidden="true"></i>
            <% end %>
            </ul>
            <ul class="list-inline duration">
              <li><%= refuge.altitude %>meters</li>
              <li><%= refuge.capacity %>people</li>
              <li><%= refuge.day_price %> €</li>
            </ul>
          </div>
          <div class="caption">
            <h4><a href="single-package-right-sidebar.html" class="captionTitle"><%= refuge.name %></a></h4>
            <h5><%= refuge.address %></h5>
            <div class="detailsInfo">
              <br>
               <%= link_to 'More Info', refuge, :class => "btn btn-primary btn"%>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  </div>
  <div class="text-center padded">
  <h1>// BECOME HOST \\</h1><br>
    <%= link_to 'Add your Shelter', new_refuge_path , :class => "btn btn-primary large" %>
  </div>
</section>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap( { provider: { scrollwheel: false }, internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/refuges/my_refuges.html.erb
<section class="mainContentSection packagesSection">
  <div class="container">
    <div class="row">
      <% @refuges.each do |refuge| %>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail deals">
        <%= cl_image_tag(refuge.photo,
      width: 400, height: 300, crop: :fill) %>
          <div class="discountInfo">
            <ul class="list-inline rating homePage">
            <% i = 0 %>
            <% ratingtotal = 0 %>
            <% refuge.reviews.each do |r| %>
            <% i += 1 %>
            <% ratingtotal += r.rating if r.rating != nil %>
            <% end %>
            <% i = ratingtotal / i if i != 0 %>
            <% i.to_i.times do %>
            <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - i.to_i).times do %>
            <i class="fa fa-star-o " aria-hidden="true"></i>
            <% end %>
            </ul>
            <ul class="list-inline duration">
              <li><%= refuge.altitude %>meters</li>
              <li><%= refuge.capacity %>people</li>
              <li><%= refuge.day_price %> €</li>
            </ul>
          </div>
          <div class="caption">
            <h4><a href="single-package-right-sidebar.html" class="captionTitle"><%= refuge.name %></a></h4>
            <h5><%= refuge.address %></h5><br><br><br>
            <div class="detailsInfo">
               <%= link_to 'Set Your Availabilities', refuge, :class => "btn btn-primary btn"%>
             <% if current_user %>
            <% if policy(refuge).edit? %>
              <td><%= link_to 'Edit', edit_refuge_path(refuge), class: "btn btn-success" %></td>
            <% end %>
            <% if policy(refuge).destroy? %>
              <td><%= link_to 'Destroy', refuge, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <%else %>
          <%end%>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  </div>
  <div class="text-center padded">
  <h1>// BECOME HOST \\</h1><br>
    <%= link_to 'Add a Shelter', new_refuge_path , :class => "btn btn-primary large" %>
  </div>
</section>

app/views/refuges/new.html.erb
<div class="banner-refuge" style="background: url('https://hd.unsplash.com/photo-1444201431989-0b9fa7488323');">


<div class="col-xs-12 col-sm-12" id="refuge">


      <%= render 'form', refuge: @refuge %>


</div>
</div>

app/views/refuges/show.html.erb
<section class="mainContentSection singlePackage">
  <div class="container">
    <div class="row countryTitle">
      <div class="col-sm-6 col-xs-12 ">
        <div id="package-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#package-carousel" data-slide-to="2" class="active"></li>
          </ol>
          <div class="carousel-inner">
            <div class="item active">
              <%= cl_image_tag @refuge.photo, crop: :fill %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12 description_refuge">
        <aside>
          <div class="weatherInfo">
           <div class="main-info">
            <h2> <%= @refuge.name %> </h2>
            <% i = 0 %>
            <% ratingtotal = 0 %>
            <% @refuge.reviews.each do |r| %>
            <% i += 1 %>
            <% ratingtotal += r.rating if r.rating != nil %>
            <% end %>
            <% i = ratingtotal / i if i != 0 %>
            <% i.to_i.times do %>
            <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - i.to_i).times do %>
            <i class="fa fa-star-o " aria-hidden="true"></i>
            <% end %>
            <%= @refuge.reviews.size %>  reviews<br><br>
            <p>Amazing shelter in <%= @refuge.address %></p>
            <h4><%= @refuge.day_price %> € per day per hiker</h4>
          </div>
          <div class="container-form">
          <div class="col-sm-8 col-xs-12" id='form-card'>
          <% if current_user %>
              <% if @refuge.user == current_user %>
              <h3> Set Your Availabilities</h3>
              <%= render partial: 'availabilities/form', refuge: @refuge, url: refuge_availabilities_path(@refuge), method: :post %>
            <% else %>
              <h3>Book this Shelter </h3>
              <%= render partial: 'bookings/form', refuge: @refuge, url: refuge_bookings_path(@refuge), method: :post %>
            <% end %>
          <% else %>
            <%= link_to 'Log-in before Booking', new_user_session_path, class: 'btn btn-success' %>
          <%end%>
          </div>
          </div>
        </div>
      </aside>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div role="tabpanel" class="countryTabs">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#over-view" aria-controls="over-view" role="tab" data-toggle="tab" aria-expanded="false">Basic Infos</a>
          </li>
          <li role="presentation" class="">
            <a href="#tour-guide" aria-controls="tour-guide" role="tab" data-toggle="tab" aria-expanded="false">Reviews</a>
          </li>
            <li class="pull-right">
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="over-view">
            <div class="row">
              <div class="col-sm-8 col-xs-12">
                <div class="commonInfo">
                  <p><%= @refuge.description %></p>
                </div>
              </div>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-guide">
            <div class="row">
              <div class="col-sm-8 col-xs-12 col-sm-offset-2">
                <% @refuge.reviews.each do |review| %>
                <div class="row_review">
                  <div class="col-md-3 text-center space-2">
                    <div class="avatar_review">
                     <% if review.user.facebook_picture_url %>
                       <%= cl_image_tag(review.user.facebook_picture_url, width: 70, height: 70) %><br>
                      <p><%= review.user.first_name %></p>
                    <% elsif review.user.profile != nil && review.user.profile.photo != nil %>
                      <%= cl_image_tag(review.user.profile.photo, width: 70, height: 70) %><br>
                        <p><%= review.user.first_name %></p>
                    <%elsif review.photo != nil %>
                      <%= cl_image_tag(review.photo, width: 70, height: 70) %><br>
                        <p><%= review.name %></p>
                    <%else%>
                      <img src="http://placehold.it/35x35" style="height: 70px; width: 70px;" ><br>
                        <p><%= review.user.first_name %></p>
                    <% end %>
                    </div>
                  </div>
                  <div class="col-md-9">
                    <div id="stars">
                      <% if review.rating != nil %>
                      <% review.rating.times do %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <% end %>
                      <% (5 - review.rating).times do %>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                      <% end %>
                      <%end%>
                    </div>
                    <div id="content_review">
                      <%= review.content %>
                    </div>
                    <div id="delete-review">
                      <% if review.user == current_user && user_signed_in? %>
                      <%= link_to "Delete", refuge_review_path(@refuge, review), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-xs" %>
                      <%end%>
                    </div>
                  </div>
                </div>
                <hr>
                <%end%>


                <hr></br></br>

                <div id="form-add-review">
                    <% if current_user && user_signed_in? && current_user.bookings != nil  %>
                      <%current_user.bookings.each do |booking| %>
                        <% if booking.status == 3 && booking.refuge.name == @refuge.name %>
                           <%= simple_form_for [@refuge, @review] do |f| %>
                              <%= f.input :reviewable_id, as: :hidden, input_html: { value: @refuge.id } %>
                              <%= f.input :reviewable_type, as: :hidden, input_html: { value: 'Refuge' } %>
                           <%= f.input :rating %>
                           <%= f.input :content %>
                           <%= f.submit "Add a new review", :class => "btn btn-primary" %>
                           <% end %>
                        <% end %>
                      <% end %>
                    <% end %>
               </div>
             </div>
           </div>
         </div>

</div>
</div>
</div>
</div>

            <div class="commonInfo">
              <div id="map" style="width: 100%; height: 600px;"></div>
              <% content_for(:after_js) do %>
              <%= javascript_tag do %>
              $(document).on('ready', function() {
              var handler = Gmaps.build('Google');
              handler.buildMap( { provider: { scrollwheel: false }, internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
      <% end %>
      <% end %>
    </div>




<div class="row">
  <div class="col-xs-12">
    <div class="sectionTitle">
      <h2><span>Shelters in the Area</span></h2><br><br>
      <div class="row">
        <% @count = 0 %>
        <% @refuges.each do |refuge| %>
        <% if refuge.range == @refuge.range && refuge.name != @refuge.name && @count < 3 %>
        <% @count += 1 %>
        <div class="col-sm-4 col-xs-12">
          <div class="relatedItem">
            <%= cl_image_tag refuge.photo, height: 270, width: 360, crop: :fill %>
            <div class="maskingInfo">
              <h4><%=refuge.name%></h4>
              <%= link_to "View more", refuge, :class => "btn buttonTransparent"%>
            </div>
          </div>
        </div>
        <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>
</div>
</section>

<div class="text-center padded">
  <% if @refuge.user == current_user %>
    <%= link_to 'Edit Your Shelter', edit_refuge_path(@refuge), class: "btn btn-success" %>
  <% else %>
  <% end%>

  <% if policy(@refuge).destroy? %>
  <td><%= link_to 'Destroy', refuge_path(@refuge), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  <%= link_to 'Back To Our Catalog', refuges_path, class: "btn btn-success" %>
</div>