config/routes.rb
Rails.application.routes.draw do
  resources :hikings do
    resources :reviews
  end
  resources :refuges do
    resources :availabilities
    resources :reviews
    resources :bookings do
      resources :payments, only: [:new, :create] do
        collection do
          get 'confirmation'
        end
      end
    end
  end
  resource :profile, controller: 'profile'


  get 'my_refuges', to: 'refuges#my_refuges'
  get 'my_bookings', to: 'bookings#my_bookings'
  resources :bookings, only: [:index] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :refuge
  monetize :amount_cents

  def pay!
    self.status = 3
    self.save!
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :accept, :reject]
  before_action :set_refuge, except: [:my_bookings, :accept, :reject]
  skip_after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized, only: :my_bookings

  # GET /bookings
  def index
    @bookings = @refuge.bookings
  end

  def my_bookings
    @user = current_user
    @bookings = @user.bookings
    @user.refuges.each do |refuge|
      @bookings += refuge.bookings
    end
  end

  # GET /bookings/1
  def show

  end

  def accept
    @booking.status = 1
    @booking.save
    redirect_to my_bookings_path
  end

  def reject
    @booking.status = 2
    @booking.save
    redirect_to my_bookings_path
  end





  # GET /bookings/new
  def new
    @booking = Booking.new
    authorize @booking
  end

  # POST /bookings
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.refuge = @refuge
    @booking.status = 0
    @booking.amount = @refuge.day_price * @booking.hikers_nb * (@booking.end_day - @booking.start_day).to_i
    authorize @booking
    respond_to do |format|
      if @booking.save
        format.html { redirect_to my_bookings_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /bookings/1
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to refuge_bookings_path, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
      authorize @booking
    end

    def set_refuge
      @refuge = Refuge.find(params[:refuge_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start_day, :end_day, :hikers_nb, :user_id, :refuge_id, :status, :payment, :amount)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def available_days(refuge)
    days = []
    a = refuge.availabilities.each do |a|
      #start: a.start_day.strftime('%m/%d/%Y'), end: a.end_day.strftime('%m/%d/%Y')
      range = (a.start_day.to_date..a.end_day.to_date).to_a
      days += range.map { |d| d.strftime('%m/%d/%Y') }
    end
    days.to_json
  end

  def booking_days(refuge)
    bdays = []
    b = refuge.bookings.each do |b|
      range = (b.start_day.to_date..b.end_day.to_date).to_a
      bdays += range.map { |d| d.strftime('%m/%d/%Y') }
    end
    bdays
  end
end

app/views/bookings/_form.html.erb
<div class="form-container">
  <%= form_for @booking, url: refuge_bookings_path(@refuge), class: 'input-daterange input-group', id: 'datepicker' do |f| %>
    <div>
    <div class="col-xs-12 col-sm-6 col-lg-6 lol">
      <%= f.text_field :start_day, id: 'dpd3', class: 'input-sm form-control', placeholder: 'check-in date'%>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-6 lol">
      <%= f.text_field :end_day, id: 'dpd4', class: 'input-sm form-control', placeholder: 'check-out date'%>
    </div>
    </div>
    <br>
    <div><br>
        <div class="col-xs-12 col-sm-6 col-lg-10 lol">
        <%= f.label :number_of_hikers %>
        <%= f.select :hikers_nb, (1..@refuge.capacity).to_a, class: ' form-control', placeholder: 'number of hikers' %>
        </div>
      <br>
      <br>
    <div class="col-xs-12 col-sm-6 col-lg-5 lol">
       <%= f.submit :class => "btn btn-success" %>
    </div>
<% end %>
</div>


<% content_for(:after_js) do %>
  <script>

    $(function () {
      var nowTemp = new Date();
      var availabilities = <%= raw available_days(@refuge) %>

      $('.input-sm').datepicker({
        beforeShowDay: function(date) {
          if (availabilities.includes(String(moment(date).format('L')))) {
            return true;
          } else {
            return false;
          }
        },
        format: 'dd/mm/yyyy',
        startDate: new Date(),
        autoclose: true,
      });

      $('#dpd3').datepicker()
        .on('changeDate', function(e) {
          $('#dpd4').datepicker('setStartDate', e.date);
        });
    });



  </script>
<% end %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start day</th>
      <th>End day</th>
      <th>Hikers nb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_day %></td>
        <td><%= booking.end_day %></td>
        <td><%= booking.hikers_nb %></td>
      </tr>
      <td><%= link_to 'Destroy', refuge_booking_path(@refuge, booking), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookings/my_bookings.html.erb
<section class="mainContentSection packagesSection">
  <div class="container">
    <% @bookings.each do |booking| %>
          <div class="row">
            <div class="col-sm-10 col-xs-12 col-sm-offset-1">
              <div class="row sidebarPage">
                <div class="col-xs-12">
                  <div class="media packagesList">
                    <a class="media-left fancybox-pop" href="img/packages/package-list-01.png">
                      <%= cl_image_tag(booking.refuge.photo, crop: :fill) %>
                    </a>
                    <div class="media-body">
                      <div class="bodyLeft">
                        <h4 class="media-heading"><a href="single-package-right-sidebar.html"><%= booking.refuge.name %></a></h4>
                        <div class="countryRating">
                          <span><%=booking.refuge.address%></span>
                          <ul class="list-inline rating">
                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                          </ul>
                        </div>
                        <ul class="list-inline detailsBtn" id="bookstatus">
                          <li><span class="textInfo"><i class="fa fa-calendar" aria-hidden="true"></i> <%= booking.start_day %></span></li>
                          <% days = (booking.end_day - booking.start_day).to_i %>
                          <li><span class="textInfo"><i class="fa fa-clock-o" aria-hidden="true"></i> <%=days%> Days</span></li>
                          <li><span class="textInfo"><i class="fa fa-male" aria-hidden="true"></i> <%= booking.hikers_nb %> Hikers</span></li>
                          <li><span class="textInfo"><%= booking.hikers_nb * booking.refuge.day_price * days unless booking.hikers_nb == nil %> €</span></li><br><br>

                          <% if booking.status == 2 %>
                            <% if booking.refuge.user == current_user %>
                              <%= link_to "Rejected", "", :class => "btn btn-danger" %>
                            <%else%>
                              <%= link_to "Rejected", "", :class => "btn btn-danger" %>
                            <%end%>
                          <%elsif booking.status == 1%>
                            <% if booking.refuge.user == current_user %>
                              <%= link_to "Accepted", "", :class => "btn btn-success" %>
                               <%= link_to "Not Paid Yet", "", :class => "btn btn-danger" %>
                            <%else%>
                              <%= link_to "Accepted", "", :class => "btn btn-success" %>
                              <%= link_to "Pay your order", new_refuge_booking_payment_path(booking.refuge, booking), :class => "btn btn-primary" %>
                            <%end%>
                          <%elsif booking.status == 0 %>
                            <% if booking.refuge.user == current_user %>
                              <%= link_to "Accept", accept_booking_path(booking), :class => "btn btn-success" %>
                              <%= link_to "Reject", reject_booking_path(booking), :class => "btn btn-danger" %>
                            <%else%>
                              <%= link_to "Not accepted yet", "", :class => "btn btn-danger" %>

                            <%end%>
                          <%else%>
                            <% if booking.refuge.user == current_user %>
                              <%= link_to "Payment Confirmed", "", :class => "btn btn-success" %>
                            <%else%>
                              <%= link_to "Payment Confirmed", "", :class => "btn btn-success" %>
                            <%end%>
                          <%end%>
                         </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
</section>