config/routes.rb
Rails.application.routes.draw do
  resources :hikings do
    resources :reviews
  end
  resources :refuges do
    resources :availabilities
    resources :reviews
    resources :bookings do
      resources :payments, only: [:new, :create] do
        collection do
          get 'confirmation'
        end
      end
    end
  end
  resource :profile, controller: 'profile'


  get 'my_refuges', to: 'refuges#my_refuges'
  get 'my_bookings', to: 'bookings#my_bookings'
  resources :bookings, only: [:index] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :refuge
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :refuge
  monetize :amount_cents

  def pay!
    self.status = 3
    self.save!
  end
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :refuge
end

app/models/hiking.rb
class Hiking < ApplicationRecord
  has_many :refuge_to_hikes
  has_many :refuges, through: :refuge_to_hikes

  has_many :reviews, as: :reviewable, dependent: :destroy
  mount_uploader :photo, PhotoUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :photo, PhotoUploader
end

app/models/refuge.rb
class Refuge < ApplicationRecord
  belongs_to :user
  has_many :availabilities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :guides
  has_many :refuge_to_hikes
  has_many :hikings, through: :refuge_to_hikes
  has_many :reviews, as: :reviewable, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  monetize :price_cents

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    if search
     return self.near(search, 50)
    else
      return Refuge.all
    end
    return nil
  end

  def availability
    capacity - bookings
  end
end

app/models/refuge_to_hike.rb
class RefugeToHike < ApplicationRecord
  belongs_to :hiking
  belongs_to :refuge
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :refuges, dependent: :destroy
  has_many :bookings, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  # GET /guides
  # GET /guides.json
  def index
    @guides = policy_scope(Guide)
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
  end

  # GET /guides/new
  def new
    @guide = Guide.new
    authorize @guide
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)
    authorize @guide

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render :show, status: :created, location: @guide }
      else
        format.html { render :new }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1
  # PATCH/PUT /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide }
      else
        format.html { render :edit }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'Guide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(:name, :email, :phone, :picture, :refuge_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized
  def home
    @refuges = Refuge.all
    @hikings = Hiking.all
    @profile = Profile.all
  end

  def navbar
    @profile = Profile.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def available_days(refuge)
    days = []
    a = refuge.availabilities.each do |a|
      #start: a.start_day.strftime('%m/%d/%Y'), end: a.end_day.strftime('%m/%d/%Y')
      range = (a.start_day.to_date..a.end_day.to_date).to_a
      days += range.map { |d| d.strftime('%m/%d/%Y') }
    end
    days.to_json
  end

  def booking_days(refuge)
    bdays = []
    b = refuge.bookings.each do |b|
      range = (b.start_day.to_date..b.end_day.to_date).to_a
      bdays += range.map { |d| d.strftime('%m/%d/%Y') }
    end
    bdays
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/hikings_helper.rb
module HikingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/refuges_helper.rb
module RefugesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myshelter.com</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>



    <%= javascript_include_tag "application" %>

  <%= yield(:after_js) %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <!-- FOOTER -->
    <footer>
      <div class="footer clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-3 col-xs-12 col-sm-offset-1">
              <div class="footerContent" id="logo">
              <%= link_to root_path, class: "navbar-wagon-brand" do %>
                  <%= image_tag "logo.png" %>
                <%end%>
              </div>
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="footerContent" >
                <h5>Contact Us</h5>
                <ul class="list-unstyled">
                  <li><i class="fa fa-home" aria-hidden="true"></i>12 rue des Tours, Lille</li>
                  <li><i class="fa fa-phone" aria-hidden="true"></i>0658038033</li>
                  <li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailTo:info@star-travel.com">infos@myshelter.com</a></li>
                </ul>
              </div>
            </div>

            <div class="col-sm-3 col-xs-12">
              <div class="footerContent">
                <h5>Newsletter</h5>
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Enter your email" aria-describedby="basic-addon21">
                  <span class="input-group-addon" id="basic-addon21"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                </div>
                <ul class="list-inline">
                  <li><a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="http://www.twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="http://www.google.com"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="http://www.pinterest.com"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="http://www.vimeo.com"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-sm-push-6 col-xs-12">
              <ul class="list-inline">
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Blog</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-sm-pull-6 col-xs-12">
              <div class="copyRightText">
                <p>Copyright © 2016. All Rights Reserved by <a target="_blank" href="http://www.iamabdus.com/">OneLoveCompany</a>.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

  </div>

  <!-- INQUIRY MODAL -->
  <div class="modal fade bookingModal modalBook" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Inquiry About Tour</h4>
        </div>
        <div class="modal-body">
          <form action="#">
            <div class="form-group">
              <input type="text" class="form-control" id="yourName" placeholder="Your Name">
            </div>
            <div class="form-group">
              <input type="email" class="form-control" id="yourEmail" placeholder="Your Email">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="phoneNumber" placeholder="Phone Number">
            </div>
            <div class="form-group">
              <textarea class="form-control" rows="3" placeholder="Message"></textarea>
            </div>
            <button type="submit" class="btn buttonCustomPrimary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.profile && current_user.profile.photo %>
            <% avatar_url = current_user.profile.photo %>
          <% else %>
            <% avatar_url = current_user.facebook_picture_url || "https://www.latoilescoute.net/IMG/jpg/visualbug-facebook1.jpg" %>
            <%end%>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <% if current_user && current_user.profile != nil %>
                <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              <% else %>
                <%= link_to new_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <%end%>
              <%end%>
            </li>
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
            <%= link_to my_bookings_path do %>
                <i class="fa fa-calendar"></i>  <%= t(".profile", default: "My Bookings") %>
              <% end %>
            </li>
            <% if current_user.refuges != nil %>
              <li>
                <%= link_to my_refuges_path do %>
                  <i class="fa fa-hotel"></i>  <%= t(".profile", default: "My Shelters") %>
                <% end %>
              </li>
            <%else%>
              <li>
                <%= link_to new_refuge_path do %>
                  <i class="fa fa-hotel"></i>  <%= t(".profile", default: "Become Host") %>
                <% end %>
              </li>
            <%end%>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <i class="fa fa fa-user"></i>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

 <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
              <% if current_user && current_user.profile != nil %>
                <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              <% else %>
                <%= link_to new_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <%end%>
              <%end%>
            </li>
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
            <%= link_to my_bookings_path do %>
                <i class="fa fa-calendar"></i>  <%= t(".profile", default: "My Bookings") %>
              <% end %>
            </li>
            <% if current_user.refuges != nil %>
              <li>
                <%= link_to my_refuges_path do %>
                  <i class="fa fa-hotel"></i>  <%= t(".profile", default: "My Shelters") %>
                <% end %>
              </li>
            <%else%>
              <li>
                <%= link_to new_refuge_path do %>
                  <i class="fa fa-hotel"></i>  <%= t(".profile", default: "Become Host") %>
                <% end %>
              </li>
            <%end%>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
      </ul>
    </div>
    <% else %>

      <!-- Login text link -->
      <i class="fa fa fa-user"></i>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%end%>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<section class="darkSectionHome">
  <div class="container">
    <div class="row gridResize">
      <form action="<%=refuges_path %>" class="">
        <div class="col-sm-3 col-xs-12">
          <div class="sectionTitleDouble">
            <p>Find</p>
            <h2>your <span>shelter</span></h2>
          </div>
        </div>
        <div class="col-sm-6 col-xs-12">
          <div class="row">
            <div class="col-sm-6 col-xs-12">
              <div class="searchTour">
                <select name="guiest_id2" id="guiest_id2" class="select-drop">
                  <option value="0">Mountain Range</option>
                  <option value="1">Alpes</option>
                  <option value="2">Pyrenees</option>
                  <option value="3">Vosges</option>
                </select>
              </div>
            </div>
            <div class="col-sm-6 col-xs-12">
              <div class="input-group date ed-datepicker">
                <%= form_tag url_for(action: 'index', controller: 'refuges'), :id => 'search', :method => :get do %>
                <%= text_field_tag :search, params[:search], placeholder: "LOCATION"%>
                <div class="input-group-addon">
                <span class="fa fa-search"></span>
              </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <%= submit_tag "Search Shelter", :address => nil, class: "btn btn-success" %>
          <% end %>
        </div>
      </form>


    </div>
  </div>
</section>