config/routes.rb
Rails.application.routes.draw do
  resources :hikings do
    resources :reviews
  end
  resources :refuges do
    resources :availabilities
    resources :reviews
    resources :bookings do
      resources :payments, only: [:new, :create] do
        collection do
          get 'confirmation'
        end
      end
    end
  end
  resource :profile, controller: 'profile'


  get 'my_refuges', to: 'refuges#my_refuges'
  get 'my_bookings', to: 'bookings#my_bookings'
  resources :bookings, only: [:index] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hiking.rb
class Hiking < ApplicationRecord
  has_many :refuge_to_hikes
  has_many :refuges, through: :refuge_to_hikes

  has_many :reviews, as: :reviewable, dependent: :destroy
  mount_uploader :photo, PhotoUploader

end

app/controllers/hikings_controller.rb
class HikingsController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]
  before_action :set_hiking, only: [:show, :edit, :update, :destroy]

  # GET /hikings
  def index
    @hikings = policy_scope(Hiking)
  end

  # GET /hikings/1
  def show
    @hikings = Hiking.all
    @hiking = Hiking.find(params[:id])


    @review = Review.new
    authorize @hiking

    refuges = @hiking.refuges

    @hash = Gmaps4rails.build_markers(refuges) do |refuge, marker|
      marker.lat refuge.latitude
      marker.lng refuge.longitude
    end


  end

  # GET /hikings/new
  def new
    @hiking = Hiking.new
    authorize @hiking
  end

  # GET /hikings/1/edit
  def edit
  end

  # POST /hikings
  def create
    if current_user.admin?
      @hiking = Hiking.new(hiking_params)
      authorize @hiking

      if @hiking.save
        redirect_to @hiking
      end
    end
  end

  # PATCH/PUT /hikings/1
  def update
    respond_to do |format|
    authorize @hiking
      if @hiking.update(hiking_params)
        format.html { redirect_to @hiking, notice: 'Hiking was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /hikings/1
  def destroy
    if current_user.admin?
      @hiking.destroy
      authorize @hiking
      respond_to do |format|
      format.html { redirect_to hikings_url, notice: 'Hiking was successfully destroyed.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hiking
      @hiking = Hiking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hiking_params
      params.require(:hiking).permit(:difficulty, :range, :description, :photo, :photo_cache)
    end
end

app/helpers/hikings_helper.rb
module HikingsHelper
end

app/views/hikings/_form.html.erb
<%= simple_form_for(@hiking) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :difficulty %>
    <%= f.input :range %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hikings/edit.html.erb
<h1>Editing Hiking</h1>

<%= render 'form', hiking: @hiking %>

<%= link_to 'Show', @hiking %> |
<%= link_to 'Back', hikings_path %>

app/views/hikings/index.html.erb
<p id="notice"><%= notice %></p>

<section class="mainContentSection packagesSection">
  <div class="container">
    <div class="row">
      <% @hikings.each do |hiking| %>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail deals">
        <%= cl_image_tag(hiking.photo,
      width: 400, height: 300, crop: :fill) %>

          <div class="caption">
            <h4><a href="single-package-right-sidebar.html" class="captionTitle"><%= hiking.name %></a></h4>
            <ul class="list-inline rating homePage">
            <% i = 0 %>
            <% ratingtotal = 0 %>
            <% hiking.reviews.each do |r| %>
            <% i += 1 %>
            <% ratingtotal += r.rating if r.rating != nil %>
            <% end %>
            <% i = ratingtotal / i if i != 0 %>
            <% i.to_i.times do %>
            <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - i.to_i).times do %>
            <i class="fa fa-star-o " aria-hidden="true"></i>
            <% end %>
            </ul>
            <h5><%= hiking.range %></h5>

            <div class="detailsInfo">
              <br>
               <%= link_to 'More Info', hiking, :class => "btn btn-primary btn"%>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  </div>

app/views/hikings/new.html.erb
<h1>New Hiking</h1>

<%= render 'form', hiking: @hiking %>

<%= link_to 'Back', hikings_path %>

app/views/hikings/show.html.erb
<section class="mainContentSection singlePackage">

      <div class="container">
            <!-- Photo et descritpion -->
            <div class="row countryTitle">
              <div class="col-sm-6 col-xs-12 ">
                <div id="package-carousel" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#package-carousel" data-slide-to="0" class=""></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="item active">
                      <%= cl_image_tag(@hiking.photo, crop: :fill) %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-xs-12 description_refuge">
                <aside>
                  <div class="weatherInfo">
                   <div class="main-info">
                      <h2> <%= @hiking.name%> </h2>
                      <% i = 0 %>
                      <% ratingtotal = 0 %>
                      <% @hiking.reviews.each do |r| %>
                      <% i += 1 %>
                      <% ratingtotal += r.rating if r.rating != nil %>
                      <% end %>
                      <% i = ratingtotal / i if i != 0 %>
                      <% i.to_i.times do %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <% end %>
                      <% (5 - i.to_i).times do %>
                      <i class="fa fa-star-o " aria-hidden="true"></i>
                      <% end %>
                        <%= @hiking.reviews.size %>  reviews<br><br>
                      <p>Amazing hiking in <%= @hiking.range %></p>
                    </div>
                    <h5>You can find the shelters of this hike below </h5>
                 <!-- <div class="row">
                  <div class="list in-line shelters">
                    <% @hiking.refuges.each do |refuge| %>
                      <div class="col-sm-4 col-xs-6"%>
                        <%= cl_image_tag( refuge.photo, width: 200, height: 150, crop: :fill) %>
                        <p><%= refuge.name %></p>
                        <%= link_to 'More Infos', refuge, :class=>'btn btn-primary btn' %>
                      </div>
                    <%end%>
                  </div>
                 </div> -->
                 </div>
            </aside>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">

                <div role="tabpanel" class="countryTabs">
                  <!-- Nav tabs -->
                  <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                      <a href="#over-view" aria-controls="over-view" role="tab" data-toggle="tab" aria-expanded="false">Basic Infos</a>
                    </li>
                    <li role="presentation" class="">
                      <a href="#tour-guide" aria-controls="tour-guide" role="tab" data-toggle="tab" aria-expanded="false">Reviews</a>
                    </li>
                    <li role="presentation" class="">
                      <a href="#refuges" aria-controls="refuges" role="tab" data-toggle="tab" aria-expanded="false">Shelters Of this Hike</a>
                    </li>
                    <li class="pull-right">
                      <ul class="list-inline">
                        <li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="http://www.google.com" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="http://www.pinterest.com" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                        <li><a href="http://www.vimeo.com" target="_blank""><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                      </ul>
                    </li>
                  </ul>
                </div>

              <!-- Tab panes -->
              <div class="tab-content">

                        <div role="tabpanel" class="tab-pane active" id="over-view">
                          <div class="row">
                            <div class="col-sm-8 col-xs-12">
                              <div class="commonInfo">
                                <p><%= @hiking.description %></p>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div role="tabpanel" class="tab-pane" id="tour-guide">
                          <div class="row">
                            <div class="col-sm-8 col-xs-12 col-sm-offset-2">
                                <% @hiking.reviews.each do |review| %>
                                  <div class="row_review">

                                      <div class="col-md-3 text-center space-2">
                                        <div class="avatar_review">
                                          <% if review.user.facebook_picture_url %>
                                             <%= cl_image_tag(review.user.facebook_picture_url, width: 70, height: 70) %><br>
                                            <p><%= review.user.first_name %></p>
                                          <% elsif review.user.profile != nil  && review.user.profile.photo != nil %>
                                            <%= cl_image_tag(review.user.profile.photo, width: 70, height: 70) %><br>
                                              <p><%= review.user.first_name %></p>
                                          <%elsif review.photo != nil %>
                                            <%= cl_image_tag(review.photo, width: 70, height: 70) %><br>
                                              <p><%= review.name %></p>
                                          <%else%>
                                            <img src="http://placehold.it/35x35" style="height: 70px; width: 70px;" ><br>
                                              <p><%= review.user.first_name %></p>
                                          <% end %>
                                        </div>
                                      </div>
                                      <div class="col-md-9">
                                          <div id="stars">
                                            <% if review.rating != nil %>
                                              <% review.rating.times do %>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                              <% end %>
                                              <% (5 - review.rating).times do %>
                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                              <% end %>
                                            <%end%>
                                          </div>
                                          <div id="content_review">
                                            <%= review.content %>
                                          </div>
                                          <div id="delete-review">
                                            <% if review.user == current_user && user_signed_in? %>
                                            <%= link_to "Delete", hiking_review_path(@hiking, review), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-xs" %>
                                            <%end%>
                                          </div>
                                       </div>

                                  </div>
                                  <hr>
                                  <%end%>
                                 <hr></br></br>
                                 <div id="form-add-review">
                                   <% if current_user && user_signed_in? && current_user.bookings != nil  %>
                                      <%current_user.bookings.each do |booking| %>
                                        <% if booking.status == 3 %>
                                          <% @hiking.refuges.each do |refuge| %>
                                            <% if booking.refuge.name == refuge.name %>
                                              <%= simple_form_for [@hiking, @review] do |f| %>
                                              <%= f.input :reviewable_id, as: :hidden, input_html: { value: @hiking.id } %>
                                              <%= f.input :reviewable_type, as: :hidden, input_html: { value: 'Hiking' } %>
                                              <%= f.input :rating %>
                                              <%= f.input :content %>
                                              <%= f.submit "Add a new review", :class => "btn btn-primary" %>
                                              <% end %>
                                            <% end %>
                                        <% end %>
                                      <% end %>
                                    <% end %>
                                  <% end %>
                                  </div>


                            </div>
                          </div>
                        </div>




                        <div role="tabpanel" class="tab-pane" id="refuges">
                          <div class="row">


                                <div class="row">
                                  <% @hiking.refuges.each do |refuge| %>
                                  <div class="col-sm-4 col-xs-12">
                                    <div class="thumbnail deals">
                                      <%= cl_image_tag(refuge.photo, crop: :fill) %>
                                      <div class="discountInfo">
                                        <ul class="list-inline rating homePage">
                                         <% i = 0 %>
                                         <% ratingtotal = 0 %>
                                         <% refuge.reviews.each do |r| %>
                                         <% i += 1 %>
                                         <% ratingtotal += r.rating if r.rating != nil %>
                                         <% end %>
                                         <% i = ratingtotal / i if i != 0 %>
                                         <% i.to_i.times do %>
                                         <i class="fa fa-star" aria-hidden="true"></i>
                                         <% end %>
                                         <% (5 - i.to_i).times do %>
                                         <i class="fa fa-star-o " aria-hidden="true"></i>
                                         <% end %>
                                       </ul>
                                       <ul class="list-inline duration">
                                        <li><%= refuge.altitude %> meters</li>
                                        <li><%= refuge.capacity %> people</li>
                                        <li><%= refuge.day_price%> €</li>
                                      </ul>
                                    </div>
                                    <div class="caption">
                                      <h4><%= refuge.name %></h4>
                                      <h5><%= refuge.address %></h5>
                                      <div class="detailsInfo">
                                        <%= link_to 'More Info', refuge, :class => "btn btn-primary btn"%>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <%end%>
                              </div>


                          </div>
                        </div>

 </div>
 </div>
 </div>
 <br>
 <br>

                                <div class="commonInfo">
                                  <div id="map" style="width: 100%; height: 600px;"></div>
                                  <% content_for(:after_js) do %>
                                  <%= javascript_tag do %>
                                  $(document).on('ready', function() {
                                  var handler = Gmaps.build('Google');
                                  handler.buildMap( { provider: { scrollwheel: false }, internal: { id: 'map' } }, function() {
                                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                                  handler.bounds.extendWith(markers);
                                  handler.fitMapToBounds();
                                  if (markers.length == 0) {
                                  handler.getMap().setZoom(2);
                                } else if (markers.length == 1) {
                                handler.getMap().setZoom(14);
                                    }
                                  });
                                });
                                <% end %>
                                <% end %>
                              </div>

 </div>
 </section>